-- Siri / Apple Shortcuts integration tables
--
-- shortcut_tokens    : stores SHA-256-hashed user tokens — raw token never persisted
-- siri_idempotency_keys : deduplicates Shortcut requests within a 5-minute window
--                         preventing double-orders if Siri fires the request twice

CREATE TABLE IF NOT EXISTS shortcut_tokens (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  token_hash   TEXT        NOT NULL UNIQUE,
  label        TEXT        NOT NULL DEFAULT 'My Shortcut',
  last_used_at TIMESTAMPTZ,
  expires_at   TIMESTAMPTZ,              -- NULL = never expires
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS shortcut_tokens_user_idx
  ON shortcut_tokens(user_id);

CREATE TABLE IF NOT EXISTS siri_idempotency_keys (
  key          TEXT        PRIMARY KEY,  -- UUID v4 generated by the Shortcut per run
  shoot_id     UUID,                     -- shoot created for this key (for replay response)
  checkout_url TEXT,                     -- Paystack URL returned (for replay response)
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at   TIMESTAMPTZ NOT NULL DEFAULT (now() + INTERVAL '5 minutes')
);

-- Index on expires_at enables fast stale-key deletion.
-- Cleanup query (run by /api/cron/cleanup-expired or a scheduled job):
--   DELETE FROM siri_idempotency_keys WHERE expires_at < now();
CREATE INDEX IF NOT EXISTS siri_idempotency_keys_expires_idx
  ON siri_idempotency_keys(expires_at);
