/**
 * Keeps the Instagram tokens alive.
 *
 * Instagram long-lived tokens last 60 days. Refreshing one resets it to a fresh
 * 60 days, but a token that goes 60 days without a refresh is dead for good and
 * has to be regenerated by hand in the Meta dashboard. That is the single most
 * likely way this whole system dies quietly, so this runs weekly rather than
 * monthly: it gives roughly eight chances to succeed before anything expires.
 *
 * Tokens live in a JSON store rather than .env.local. Rewriting .env.local from
 * a cron job risks corrupting the file every other secret depends on; the store
 * is seeded from the environment on first run and owned by this script after.
 *
 *   node --env-file=.env.local scripts/instagram-refresh.mjs [--dry-run]
 */
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";

const DRY = process.argv.includes("--dry-run");
const DATA_DIR = process.env.INSTAGRAM_DATA_DIR || "/home/aluxart/instagram-data";
const STORE = path.join(DATA_DIR, "tokens.json");
const TG_TOKEN = process.env.TELEGRAM_BOT_TOKEN;
const TG_ADMIN = process.env.TELEGRAM_ADMIN_CHAT_ID;

// Refresh once a token is older than this. Instagram refuses to refresh a token
// less than 24 hours old, so never go below a day.
const REFRESH_AFTER_DAYS = 7;
// Shout well before the cliff, not at it.
const WARN_BELOW_DAYS = 20;

const log = (...a) => console.log(new Date().toISOString(), "[ig-refresh]", ...a);

async function tellAdmin(text) {
  if (!TG_TOKEN || !TG_ADMIN) return log("no telegram credentials — cannot alert");
  await fetch(`https://api.telegram.org/bot${TG_TOKEN}/sendMessage`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ chat_id: TG_ADMIN, text, parse_mode: "HTML", disable_web_page_preview: true }),
  }).then(r => r.json()).then(j => { if (!j.ok) log("telegram failed:", JSON.stringify(j).slice(0, 140)); })
    .catch(e => log("telegram error:", e.message));
}

/** First run: build the store from whatever .env.local was given. */
function seedFromEnv() {
  const handles = (process.env.IG_ACCOUNTS || "").split(",").map(s => s.trim()).filter(Boolean);
  const out = {};
  for (const h of handles) {
    const key = h.toUpperCase();
    const token = process.env[`IG_${key}_TOKEN`];
    const id = process.env[`IG_${key}_ID`];
    if (!token || !id) { log(`skipping ${h} — missing IG_${key}_TOKEN or _ID`); continue; }
    out[h] = { id, token, refreshedAt: new Date().toISOString(), expiresAt: null };
  }
  return out;
}

async function main() {
  await mkdir(DATA_DIR, { recursive: true });

  let store = existsSync(STORE) ? JSON.parse(await readFile(STORE, "utf8")) : null;
  if (!store || Object.keys(store).length === 0) {
    store = seedFromEnv();
    log(`seeded store with ${Object.keys(store).length} account(s) from the environment`);
  }

  const problems = [];
  const refreshed = [];

  for (const [handle, acct] of Object.entries(store)) {
    const ageDays = (Date.now() - new Date(acct.refreshedAt || 0).getTime()) / 86400000;
    const leftDays = acct.expiresAt
      ? Math.round((new Date(acct.expiresAt).getTime() - Date.now()) / 86400000)
      : null;

    if (leftDays !== null && leftDays < WARN_BELOW_DAYS) {
      problems.push(`${handle}: only ${leftDays} day(s) of token left`);
    }

    if (ageDays < 1) { log(`${handle}: refreshed ${ageDays.toFixed(1)}d ago — too new to refresh, skipping`); continue; }
    if (ageDays < REFRESH_AFTER_DAYS) { log(`${handle}: ${ageDays.toFixed(1)}d old, ${leftDays ?? "?"}d left — no action`); continue; }

    if (DRY) { log(`${handle}: DRY RUN — would refresh (${ageDays.toFixed(1)}d old)`); continue; }

    try {
      const r = await fetch(
        `https://graph.instagram.com/refresh_access_token?grant_type=ig_refresh_token&access_token=${acct.token}`
      ).then(x => x.json());

      if (r.error) throw new Error(r.error.message || JSON.stringify(r.error));
      if (!r.access_token) throw new Error("no access_token in response");

      // Confirm publishing survived the refresh — a token that comes back without
      // it would post nothing and the failure would only show at posting time.
      const perms = (r.permissions || "").split(",");
      if (!perms.includes("instagram_business_content_publish")) {
        problems.push(`${handle}: refreshed token LACKS content_publish permission`);
      }

      acct.token = r.access_token;
      acct.refreshedAt = new Date().toISOString();
      acct.expiresAt = new Date(Date.now() + (r.expires_in ?? 0) * 1000).toISOString();
      refreshed.push(`${handle} (+${Math.round((r.expires_in ?? 0) / 86400)}d)`);
      log(`${handle}: refreshed, now valid ${Math.round((r.expires_in ?? 0) / 86400)} days`);
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      problems.push(`${handle}: refresh FAILED — ${msg.slice(0, 120)}`);
      log(`${handle}: refresh failed —`, msg);
    }
  }

  if (!DRY) await writeFile(STORE, JSON.stringify(store, null, 2));

  if (problems.length) {
    await tellAdmin(
      "⚠️ <b>Instagram tokens need attention</b>\n\n" + problems.map(p => "• " + p).join("\n") +
      "\n\nA token that goes 60 days without a refresh cannot be recovered — it has to be " +
      "regenerated in the Meta dashboard. Worth looking today."
    );
  } else if (refreshed.length) {
    await tellAdmin("🔄 <b>Instagram tokens refreshed</b>\n\n" + refreshed.map(r => "• " + r).join("\n") +
      "\n\nNothing needed from you. Next check in a week.");
  } else {
    log("nothing due — no alert sent");
  }
}

main().catch(async (e) => {
  const msg = e instanceof Error ? e.message : String(e);
  console.error(new Date().toISOString(), "[ig-refresh] ERROR:", msg);
  await tellAdmin(`❌ <b>Instagram token refresh crashed</b>\n\n<code>${msg.slice(0, 300)}</code>\n\nTokens are NOT being renewed until this is fixed.`);
  process.exit(1);
});
